### PR TITLE
Discussion/Suggestion: edit metadata or add data for each row?

### PR DESCRIPTION
**Pull request by philter87**
## Description

- This PR moves the "edit metadata" and "add data" buttons to a "more"-button on each row. See picture below. Something confused Omar about the buttons, but I am not sure what. This is just a suggestion based on the "User management" wireframes, where actions are added to a "more"-button.

### Suggestion 1:
image

### Suggestion 2:
image

### Suggestion 3:
image

### Suggestion 4
image

## Testing

- [ ] Yes
- [X] No, not needed (give a reason below)
- [ ] No, I need help writing them

Not possible to test and it is just a suggestion 

## Reviewer Focus
This PR only needs a quick review.

The code is not so difficult, but from a UX perspective is this okay?

## Checklist

For all PRs that are not general documentation

- [ ] Tests accompany or reflect changes to the code
- [X] Tests ran and passed locally
- [X] Ran the linter and formatter
- [X] Build has passed locally
- [X] Relevant documentation has been updated

### CODE REVIEW

**Review by signekb — COMMENTED** [review]
Ah, that was the vision you mentioned yesterday! In some ways I like it, in others I'm not so sure. Like: wouldn't it look a bit "empty" for a user who can only import data (where the "create metadata" button won't be showed)?

**Comment by philter87** [comment]
> Ah, that was the vision you mentioned yesterday! In some ways I like it, in others I'm not so sure. Like: wouldn't it look a bit "empty" for a user who can only import data (where the "create metadata" button won't be showed)?

I think we should aim for a simple/empty look, but you are right in the sense that the "import data" button is more hidden and might be hard to find.

But maybe there is a better solution. I just sensed that Omar was confused about something with the buttons, but it could have just been the "wording" in the buttons.

**Comment by henrik-goul** [comment]
My gut feeling is that "add data" should have its own button, but "edit metadata" could fit well in the "more"-menu :)

**Comment by signekb** [comment]
Ah, so the two "adding" actions are shown as buttons and editing the metadata could be seen as a "more" action? 
That also makes sense to me :)

**Comment by signekb** [comment]
@philter87 and I just talked about that the current implementation is missing the "unfold" icon that's in the wireframes 
Untitled

**Comment by lwjohnst86** [comment]
We'll keep thinking about this. Could be the buttons could be less "bold" or softer to not be too noisy. We'll look at this again after implementing more of the look and feel applied.

**Comment by signekb** [comment]
@henrik-goul : It's a balance between the buttons looking active and inactive. I would like the upload icon more than the plus icon

**Comment by lwjohnst86** [comment]
Given that we're doing a decent amount of refactoring and redesigning, we'll close this for now since it would require a lot of fixing to be relevant now.

**Comment by signekb** [comment]
@lwjohnst86 Wouldn't this still be relevant when we start looking at the UI again?

**Pull request closed without merging**
