### PR TITLE
style: :memo: Use more natural language to describe error message.

### PR DESCRIPTION
**Pull request by lwjohnst86**
## Description

- This PR removes a duplicate test I accidentally added as well as updates the text for error messages to be more natural language and hopefully a bit clearer.

## Reviewer Focus

This PR only needs a quick review.

## Checklist

For all PRs that are not general documentation

- [ ] Tests accompany or reflect changes to the code
- [ ] Tests ran and passed locally
- [x] Ran the linter and formatter
- [ ] Build has passed locally
- [x] Relevant documentation has been updated

### CODE REVIEW

**Comment by lwjohnst86** [comment]
Nice catch @signekb!

**Review by lwjohnst86 — COMMENTED** [review]
Copied code incorrectly and forgot to revise after pasting.

**Review by signekb — APPROVED** [review]
👍

**Comment by signekb** [comment]
@lwjohnst86 are we linting twice now? 
Screenshot 2024-02-13 at 09 46 07

**Pull request merged**
