### PR TITLE
fix: :bug: sort ids before returning them

### PR DESCRIPTION
**Pull request by martonvago**
## Description

This sorts IDs before returning them. It seems to be the case that the order in which dirs are returned is not determined by Python, which can lead to some inconsistent behaviour. This is causing some tests to fail remotely, but not locally (for me at least). 

Even more interestingly, the tests are run for PRs where neither one of the participating branches even has the commit with the test (🤔). I have no idea why and this does nothing to resolve that.

## Reviewer Focus

This PR needs a quick review.

Focus on CHANGES.

## Checklist

- [x] Added or updated tests
- [x] Tests passed locally
- [x] Linted and formatted code
- [x] Build passed locally
- [x] Updated documentation

### CODE REVIEW

**Review by signekb — COMMENTED** [review]
Couldn't we sort the ids in the tests instead? 
Or is this bc it's just nice to ensure that the ids are always sorted when used in e.g., error messages? :)

**Comment by signekb** [comment]
About the whole problem: Could this be due to a bump in dependencies that change the sorting behaviour somehow? It seems that #712 started failing after Luke merged `main` into it on 3 October, and I can see that we  bumped `frictionless` (among others) on `main` on 1 October? 
I think that the `test` action just runs all tests on the branch, independently of whether there are any commits related to that test 🌻

**Comment by martonvago** [comment]
Yeah, I thought we might as well sort the ids before passing them to the error message, but I don’t feel very strongly about it.

**Comment by martonvago** [comment]
Yeahhh, it could be that somehow the dependencies affected the sorting, but I think we’re only using `pathlib` for it, so it would need to be in some complicated way. At least I couldn’t figure out how or why when I looked at it last week. But I also think that the key to it lies in pinpointing when exactly main started failing.

If you look at [this merged PR](https://github.com/seedcase-project/seedcase-sprout/pull/743), this has the dependency updates from 1 Oct and yet all tests passed, so that confuses things a bit.

But `test` shouldn’t run tests that don’t exist at all on the two branches involved in the PR, right?

**Comment by signekb** [comment]
Ah, you're right! My bad. Yeah, this requires some detective work 🕵️ 

I'm not sure what you mean with the last part? Which two branches are you referring to? 
Since #730 has been merged to `main` and `main` has been merged to #744, the failing tests do exist on that branch, right?

**Comment by signekb** [comment]
BUT, maybe this discussion of the origin of the issue should be moved out of this PR?

**Review by signekb — APPROVED** [review]

**Comment by signekb** [comment]
I think that this is PR is a non-controversial solution to the problem, so I'll merge it 👍

**Pull request merged**
