### PR TITLE
Feat/add original column name

### PR DESCRIPTION
**Pull request by signekb**
## Description

- This PR adds the original column name, `original_name` to the `ColumnMetadata` model and adds it to the `file_upload` view. 
- The user will be able to edit the name and title of the column (machine-friendly and human-readable names), but not the original column name. This ensures that we have a reference when users want to add data to an existing table. 
- To be able to add a new field in the `ColumnMetadata` model without a default, I deleted the  `0001_initial` migration and built it again.

## Reviewer Focus

This PR only needs a quick review.
- Have I missed somewhere where `original_name` needs to be added? I'm thinking that @K-Beicher will add this to the column review PR #149 
- I haven't added any tests for this. Should I? 

## Checklist

For all PRs that are not general documentation

- [X] Tests accompany or reflect changes to the code (no tests added)
- [X] Tests ran and passed locally
- [X] Ran the linter and formatter
- [X] Build has passed locally
- [X] Relevant documentation has been updated

### CODE REVIEW

**Review by philter87 — APPROVED** [review]
Looks good! At some point, we might need to add default values, but I see why you wanted to redo the initial migration

**Comment by signekb** [comment]
@philter87 Should we though? I asked @K-Beicher about this. If there's missing a header in the csv, wouldn't it make sense for us to throw an error?

**Review by lwjohnst86 — APPROVED** [review]
Simple enough, awesome!

**Comment by philter87** [comment]
> @philter87 Should we though? I asked @K-Beicher about this. If there's missing a header in the csv, wouldn't it make sense for us to throw an error?

Yes, we should throw an error if a header is missing, but my point was something different.

In the future, we should not change migrations after they have already been deployed/applied, because Django only applies a migration once. So if our application was running somewhere for real, then this new column would not be added. 
Therefore we would need to either allow nulls or add default values somehow when adding columns. In this case, however, it would be a little difficult to fix existing rows (except we could use the maybe name or title as default values)

But for now it is perfectly okay. It was just a small note (which was a bit hard to understand)

**Comment by signekb** [comment]
Ahh, yes, I see! Thanks for elaborating!

**Pull request merged**
