### PR TITLE
feat: Values preserved between view switches

### LINKED ISSUE #317: Saving input when switching views (related to update all without needing required fields)
Connected to a few other issues, about saving things to return to it later.

### PR DESCRIPTION
**Pull request by philter87**
## Description

- This PR adds a feature. On 'column-review.html', the input values are preserved when switching between table view and grid view.

## Related Issues

Closes #317 

## Testing

- [ ] Yes
- [X] No, not needed (give a reason below)
- [ ] No, I need help writing them

I was unable to write tests for this as it is javascript

## Reviewer Focus
**This is a small PR, but I need some help to figure out if this is the correct solution**. 

I decided to move the input values with Javascript and not persist the values when switching views. From my perspective, this is what the user expects... But I can easily be persuaded to change this?

## Checklist

For all PRs that are not general documentation

- [ ] Tests accompany or reflect changes to the code
- [X] Tests ran and passed locally
- [X] Ran the linter and formatter
- [X] Build has passed locally
- [X] Relevant documentation has been updated

### CODE REVIEW

**Review by signekb — COMMENTED** [review]
When I test it by adding a description in the card view and switch to table view, the description is not shown in the table view. However, the value is preserved in the sense that when I return to card view, it's still there. 

So, I'm thinking that this isn't working as expected? :)

**Comment by philter87** [comment]
> When I test it by adding a description in the card view and switch to table view, the description is not shown in the table view. However, the value is preserved in the sense that when I return to card view, it's still there.
> 
> So, I'm thinking that this isn't working as expected? :)

You are right. I failed to correctly rename a variable. It works now

**Review by signekb — CHANGES_REQUESTED** [review]
Ah, nice! It seems that column names and descriptions update as expected when I switch view, but the data types doesn't? So, something's still not quite right? :)

**Review by lwjohnst86 — CHANGES_REQUESTED** [review]
Both the display name and description get changed but the data type doesn't.

**Comment by philter87** [comment]
Fixed: DataType and Excluded flag are now preserved when switching views

**Review by K-Beicher — APPROVED** [review]
All fields now seem to work as expected, looks great!

**Review by lwjohnst86 — APPROVED** [review]

**Pull request merged**
