### PR TITLE
style: rename column names

### LINKED ISSUE #234: Discussion: Should we rename column "original name", "header" and "title" to something more intuitive?
I think that I'm not alone in never being able to remember which one is the "machine readable" one, and which is the "human readable" one. 

Talking to @K-Beicher about some of them, we have the following suggestions:
`original column name` --> `extracted column name`
`title` (the human readable name) --> `display name`
`header` (the machine readable name) --> `variable name` ?? 

Please chime in with ideas to make this more intuitive @philter87 @lwjohnst86 @K-Beicher 

(Assigning myself as the one to ensure this discussion moves forward and will be resolved)

### PR DESCRIPTION
**Pull request by signekb**
## Description

- This PR changes the names we use to describe column names in accordance with issue #234 

- `original_name` -> `extracted_name`
- `name` -> `machine_readable_name`
- `title` -> `display_name`

- In addition, I have added some minor changes to the wording in help dialog in `column-review.html`
- Since I have automatic formatting in my VSCode, the `html` indents were fixed as well. 

## Related Issues

Closes #234 

## Testing

- [ ] Yes
- [X] No, not needed (give a reason below)
- [ ] No, I need help writing them

Did not add any need code (but did alter tests to fit the new naming of columns)

## Reviewer Focus

This PR only needs a quick review.

## Checklist

For all PRs that are not general documentation

- [X] Tests accompany or reflect changes to the code
- [X] Tests ran and passed locally
- [X] Ran the linter and formatter
- [X] Build has passed locally
- [X] Relevant documentation has been updated

### CODE REVIEW

**Review by philter87 — APPROVED** [review]
A bit hard to keep track, but it works when I run it locally

**Comment by signekb** [comment]
@philter87 Yeah, sorry about that!

**Comment by philter87** [comment]
> @philter87 Yeah, sorry about that!

No prob :) 

I should have added, that this is unavoidable on stuff like this. 
The comment was more a disclaimer on how thorough I was :)

**Comment by signekb** [comment]
> > @philter87 Yeah, sorry about that!
> 
> No prob :)
> 
> I should have added, that this is unavoidable on stuff like this. The comment was more a disclaimer on how thorough I was :)

Also totally fair. I don't think this requires a very thorough review :)

**Review by lwjohnst86 — APPROVED** [review]

**Pull request merged**
