### PR TITLE
feat: adding style to Kris' work

### LINKED ISSUE #270: Column-review. Suggestion for illustrating column metadata
This address two problems: 
1. User experiments show that people find it a bit confusing that column metadata is displayed as rows. 
2. @lwjohnst86 wanted to show preview data (how does the data look after inferred types)

Based on @K-Beicher's work, I have styled two suggestions

## 1# Suggestion
Image

When the edit button is clicked for one of the columns, then a dialog opens:
Image

Problems:
1. We will need to add horizontal scrolling, when several columns are added
5. It requires more clicks to fill description. We might help the user a bit by adding a button "Next column" in the dialog

## 2# Suggestion
image

### PR DESCRIPTION
**Pull request by philter87**
## Description

- This PR adds a new view on the column metadata. It is based on Kris' "column-review-list", but I also added a data preview. Note: I did not replace 'column-review-list', I just copy-pasted so when we decide on a layout, we probably need to delete something.

image

## Related Issues

Closes #270 

## Testing

- [X] Yes
- [ ] No, not needed (give a reason below)
- [ ] No, I need help writing them

## Reviewer Focus
This PR requires an in-depth review.

Focus should be on two files:
- metadata-review.html
- metadata_review.py
- The other changes are less important. I have touched many files as I have removed "original_name" and "id" from the ColumnMetaDataForm as these should not be changed by the user. This also affected 'metadata-review.html' and 'metadata-review-list.html'. 

## Checklist
For all PRs that are not general documentation

- [X] Tests accompany or reflect changes to the code
- [X] Tests ran and passed locally
- [X] Ran the linter and formatter
- [X] Build has passed locally
- [X] Relevant documentation has been updated

### CODE REVIEW

**Review by lwjohnst86 — DISMISSED** [review]
I like this alot! 🎉

**Comment by philter87** [comment]
Damn, I merged the tabindex-stuff into this branch

**Comment by lwjohnst86** [comment]
hihi, no worries, I can fix it if you need help/don't want to deal with it ☺️

**Comment by lwjohnst86** [comment]
@philter87 did you want it removed? Or you want it kept? If you want it kept, we can keep it as is in here.

**Comment by philter87** [comment]
> @philter87 did you want it removed? Or you want it kept? If you want it kept, we can keep it as is in here.

I just wanted to merge it into main, but forgot that it was stacked (and the PR is already big)

**Comment by K-Beicher** [comment]
I started writing a comment and realised that we need a full discussion post on the subject of which variable names we will allow the user to be able to edit.  I'm going to go create that,  and then update here with the id.

**Review by lwjohnst86 — APPROVED** [review]

**Pull request merged**
