### PR TITLE
Feat/update edit metadata flow to include stepper

### PR DESCRIPTION
**Pull request by signekb**
## Description

- This PR adds a metadata_id_update page with the stepper.
- This has been done rather quickly, so there are some suboptimal workarounds.... 
- Missing one thing: To redirect to homepage after second step!

## Related Issues

Closes #...

See also Issues #...

## Testing

- [ ] Yes
- [ ] No, not needed (give a reason below)
- [ ] No, I need help writing them

## Reviewer Focus

This PR only needs a quick review.
This PR requires an in-depth review.

## Checklist

For all PRs that are not general documentation

- [ ] Tests accompany or reflect changes to the code
- [ ] Tests ran and passed locally
- [ ] Ran the linter and formatter
- [ ] Build has passed locally
- [ ] Relevant documentation has been updated

For general documentation:

- [ ] Spell-check
    - [ ] US
    - [ ] UK
- [ ] Did the page(s) preview correctly on your machine without breaking
- [ ] New category words (keywords) (if any) added to the code snippet file

### CODE REVIEW

**Review by lwjohnst86 — COMMENTED** [review]
Super neat! I loaded it up and tested it out, but one thing I noticed is you *need* to make changes to the table name to continue. I tried to keep it readonly but it doesn't allow me to continue because it is set as required in the form. So we might need to create another form for it maybe.. But we'll do this later, I won't have time to dig in and figure out how to fix that.

**Comment by signekb** [comment]
@lwjohnst86 Hmmm, what do we want to do with this? 
It seems like we'll do a lot of refactoring anyway, so not sure this is even relevant anymore?

**Comment by lwjohnst86** [comment]
@lwjohnst86 great question. I am also wondering about that with my own draft PRs... Maybe it makes sense to close it? I'll leave it up to you to decide what you want to do. I might close mine, but I'll think about it.

**Comment by signekb** [comment]
@lwjohnst86 I will close it, since the refactoring work we're doing currently should make the suboptimal workarounds that me and Philip did unnecessary.

**Pull request closed without merging**
